import type { NextPage } from 'next'
import Head from 'next/head'
import getConfig from 'next/config'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const {
    publicRuntimeConfig: {
      storybookUrl,
      nextAuthUrl,
    }
  } = getConfig()
  return (
    <div className={styles.container}>
      <Head>
        <title>reproduce vercel --env issue with Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <table>
          <thead>
            <tr>
              <th>Env variable</th>
              <th>Value</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>STORYBOOK_URL</td>
              <td><code>{storybookUrl}</code></td>
            </tr>
            <tr>
              <td> NEXTAUTH_URL</td>
              <td><code>{nextAuthUrl}</code></td>
            </tr>
         </tbody>
        </table>
      </main>

      <style global jsx>{`
        table {
          border-collapse: collapse;
        }
        td, th {
          border: 1px solid #777;
          padding: 0.5rem;
        }
        code {
            background-color: #eee;
            padding: 0.25rem 0.5rem;
            border-radius: 0.25rem;
        }
      `}</style>

    </div>
  )
}

export default Home
